version: '3.8'

services:
  # PHP + Laravel Service
  app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - node
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=192.168.1.10
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}

  # Nginx service to reverse proxy requests to Laravel
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    depends_on:
      - app
    networks:
      - app-network

  # Node.js service to compile assets (Tailwind, Alpine.js, etc.)
  node:
    image: node:18-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    command: ["sh", "-c", "npm install && npm run dev"]

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
