version: '3.8'

services:
  app:
    image: menu-image
    container_name: menu-planner
    build:
      context: .
      dockerfile: './Dockerfile'
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '81:80'
    volumes:
      - ./:/var/www/service
    networks:
      - app-network

networks:
  app-network:
    external: true
